### ISSUE TITLE
Can't build with trunk on Windows

### ISSUE THREAD

**Issue by oceantume** [rustgameexperts/bevy-shell-template#23]
The pre_build hook in `Trunk.toml` uses the `cp -r` command to move the assets into the launcher folder, but that command doesn't exist on Windows. If possible, a Windows-specific pre_build hook should be used when running on that platform, or another mechanism should be used to copy the files.

To reproduce, simply run `trunk build` or `trunk serve` on Windows.

I've looked into the trunk docs a little bit and I'm not sure what the simplest solution would be here.

**Comment by JSmith-LDG** [comment]
I had the same issue on windows, I fixed it by changing the hook to this:
```
command = "xcopy"
command_arguments = ["assets", "launchers/wasm/"]
```

**Comment by simbleau** [comment]
Likely the best scenario is a build script to copy the files. This could be platform agnostic.

Pull requests are appreciated.

**Comment by simbleau** [comment]
unfortunately I've decided this won't be worked on because I think the audience is too narrow...

In the future, if you encounter this issue, simply download a modern terminal emulator like git bash to ensure the commands will work.
